# Site setings
name: 'Ravi.ai'
description: 'This is the place where I write articles in area of deep learning.'
meta_description: 'Jekyll template, minimal style, perfect for bloggers.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: 
disqus: 
mailchimp_url:
cover_image: bc_1.jpg
# Add your GA Tracking Id
ga_analytics: 


# Author
author:
  name: 'Raviteja Ganta'
  image: 'Profile_pic1.jpg'
  greetings: 'Hi there!'
  description: "My name is Raviteja Ganta. I'm a data scientist."
  bio: 'Raviteja is a data scientist. He loves building Machine learning and deep learning solutions. Aspring deep learning researcher.'

# Contact form setings
email: ravitejareddy.ganta@gmail.com
#contact_page_description: "Horace theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want."
#thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
# twitter: 'username'
# facebook: 'username'
github: 'raviteja-ganta'
# codepen: 'username'
# dribbble: 'username'
# medium: '@username'
# instagram: 'username'
# pinterest: 'username'
# linkedin: 'username'
# producthunt: '@username'

# Navigation
navigation:
  - text: About
    url: /about/
  - text: Style Guide
    url: /style-guide/
  - text: Contact Me
    url: /contact/

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
